### ISSUE TITLE
Target CentOS 8

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/k8-reverse-proxy#41]
We need to retest the deployment but targeting CentOS, the code to be test is this one:
https://github.com/k8-proxy/k8-reverse-proxy/tree/develop/stable-src

**Comment by IslamHeggy** [comment]
I already have a packer template with Ansible for creating the OVA with CentOS7 @mahnouman

**Comment by mahnouman** [comment]
> I already have a packer template with Ansible for creating the OVA with CentOS7 @mahnouman

Thanks @IslamHeggy , then yes we can jump into testing that.

**Comment by mahnouman** [comment]
@IslamHeggy Can you please pin this out, i.e. the code targeting CentOS OVA? Thanks

**Comment by Abby595** [comment]
Tested and failed at the Deployment step: **docker-compose up -d** without sudo 
![c2](https://user-images.githubusercontent.com/71430578/94009930-76a24a80-fda5-11ea-815b-2c29f4a7a6a1.PNG)
![c3](https://user-images.githubusercontent.com/71430578/94009895-65f1d480-fda5-11ea-8449-b8da0951366a.PNG)
![c4](https://user-images.githubusercontent.com/71430578/94009900-67bb9800-fda5-11ea-9225-eb191a2fac4c.PNG)

There was an error while installing docker in this command **sudo sh get-docker.sh**, due to the following missing dependencies:

1. containerd.io-1.3.7-3.1.el8.x86_64.rpm 
2. docker-ce-19.03.13-3.el8.x86_64.rpm  
3. docker-ce-cli-19.03.13-3.el8.x86_64.rpm

After manually installing them from (https://download.docker.com/linux/centos/8/x86_64/stable/Packages/), still the same error while using any docker-compose command.

**Comment by Abby595** [comment]
Tested it again after using these commands:
usermod -aG docker $USER
systemctl enable --now docker
docker-compose up -d --force-recreate
![test2](https://user-images.githubusercontent.com/71430578/94013676-b0298480-fdaa-11ea-9763-9401a97867f4.PNG)

**Comment by mahnouman** [comment]
Thanks @Abby595 for the review
